### ISSUE TITLE
Add Ahsoka TV Series

### ISSUE THREAD

**Issue by normous** [SirIndubitable/mcu-calendar#112]
https://www.themoviedb.org/tv/114461-ahsoka

**Comment by SirIndubitable** [comment]
Oh thanks! I just added the "Star Wars" tag, I'll make sure that the auto update tonight catches that show.

**Comment by SirIndubitable** [comment]
Hmm I'm not sure why it didn't update, I'm wondering if there is something wrong with the Auto Update workflow.  
I went ahead and added it manually though
