### ISSUE TITLE
Pull requests of updates haven't been merged

### ISSUE THREAD

**Issue by virenratan** [SirIndubitable/mcu-calendar#269]
It looks like there are a few months worth of updates sitting in open pull requests, so the information in the calendars is quite out of date.

**Comment by SirIndubitable** [comment]
The auto updates post every day if something new is created.  So if I miss a few days on reviews it usually ends up creating 4 identical PRs.  I haven't gone through deleting those old ones yet.  

A new PR posted yesterday that I was going to look at today.  I can manually fix stuff if you know of any specific information is out of date though.

**Comment by SirIndubitable** [comment]
Ah yeah, it doesn't handle when movies change names (even slightly) I really need to fix that.

Once I get to a proper computer I'll go ahead and manually fix the duplicates though.  If it's mostly duplicates, I can look for others easily enough.  Thanks for pointing that out!

**Comment by SirIndubitable** [comment]
I think I cleaned up the duplicates and am handling the webscraping better for renamed movies now.  
Also added tests to make sure we don't run into multiple movies with the same imdb id.  
Going to close this out, as I think I fixed all of the duplicates I could find
