### ISSUE TITLE
Update on starwars calendar

### ISSUE THREAD

**Issue by rkristelijn** [SirIndubitable/mcu-calendar#63]
It seems that the mandalorian season 3 is not in;

Can I create a pull request to put it there? is there a manual for it?

https://www.ign.com/articles/upcoming-new-star-wars-movies-2023-tv-shows-release-dates

**Comment by SirIndubitable** [comment]
The [README](https://github.com/SirIndubitable/mcu-calendar#adding-or-updating-media-information) for the repo talks about the ways to update or add media information.

The easiest one being to ensure the metadata on www.themoviedb.org is correct and it should be automatically updated everyday.

It looks like the Madalorian did not have the "Star Wars" tag.  I updated it and it so it should update by tomorrow.

**Comment by rkristelijn** [comment]
Thanks @SirIndubitable Just to validate, my calendar doesn't update (yet), only shows 'the bad batch', nothing else planned for star wars.

**Comment by SirIndubitable** [comment]
@rkristelijn Thanks for noticing that! The script that was previously creating Pull requests for the auto update no longer worked.  I fixed the script and it should now be working and updating.

**Comment by rkristelijn** [comment]
Just validated it works for mando
