### ISSUE TITLE
Unable to push to repo

### ISSUE THREAD

**Issue by virenratan** [SirIndubitable/mcu-calendar#8]
I don't seem to be able to contribute to the repo. I can clone, fetch and pull okay, but when I try to push a branch to remote I'm getting the following:

```
Pushing to github.com:SirIndubitable/mcu-calendar.git
ERROR: Permission to SirIndubitable/mcu-calendar.git denied.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights and the repository exists.
```

I was trying to push a branch to update the Hawkeye season length to 5 weeks, based on [TV Time](https://www.tvtime.com/en/show/367146).

**Comment by SirIndubitable** [comment]
The process I've seen most often on github open source repos is to first fork it, then make changes on your version of the repo, then create a pull request for this repo.  
https://daily.dev/blog/how-to-contribute-to-open-source-projects-as-a-beginner
